name: Build Wheels

on:
  push:
    branches:
      - main

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    if: github.repository_owner == 'simon-stahlberg'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies and requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel twine cibuildwheel delocate

    - name: Build wheels
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          cibuildwheel --platform linux --output-dir wheelhouse;
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          cibuildwheel --platform macos --output-dir wheelhouse;
        fi
      env:
        CIBW_BUILD_VERBOSITY: "1"
        CIBW_ARCHS_MACOS: "arm64"

    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload --skip-existing --repository-url https://upload.pypi.org/legacy/ wheelhouse/*
