name: Build Wheels

on:
  push:
    branches:
      - main

jobs:
  build_wheels:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        platform: ["manylinux2014_x86_64", "manylinux2014_i686", "manylinux2014_aarch64", "manylinux2014_ppc64le", "manylinux2014_s390x"]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    if: github.repository_owner == 'simon-stahlberg'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "${{ matrix.python-version }}"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade twine cibuildwheel

    - name: Build wheels
      run: cibuildwheel --output-dir wheelhouse
      env:
        CIBW_PLATFORM: "${{ matrix.platform }}"
        CIBW_BUILD: "cp${{ matrix.python-version | replace('.', '') }}-*"
        CIBW_BUILD_VERBOSITY: "1"
        CIBW_ARCHS_MACOS: "arm64"

    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload --skip-existing --repository-url https://upload.pypi.org/legacy/ wheelhouse/*
