name: Build Wheels for macOS

on:
  push:
    branches:
      - main

jobs:
  build_wheels:
    strategy:
      matrix:
        python-version: ["cp39", "cp310", "cp311", "cp312", "cp313"]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}

    if: github.repository_owner == 'simon-stahlberg'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"  # Use a fixed version for the setup step

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade twine cibuildwheel

    - name: Build wheels
      run: cibuildwheel --output-dir wheelhouse --verbose
      env:
        CIBW_PLATFORM: "macos"
        CIBW_BUILD: "${{ matrix.python-version }}-*"
        CIBW_ARCHS: "arm64"  # Only build for Apple Silicon
        CIBW_BUILD_VERBOSITY: "1"

    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload --skip-existing --repository-url https://upload.pypi.org/legacy/ wheelhouse/*
