name: Build Wheels

on:
  push:
    branches:
      - main

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    if: github.repository_owner == 'simon-stahlberg'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies and requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel twine cibuildwheel

    - name: Build wheels
      run: cibuildwheel --platform linux --output-dir wheelhouse
      env:
        CIBW_BUILD_VERBOSITY: "1"
      CIBW_BEFORE_BUILD: |
          curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
          bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
          export PATH="$HOME/miniconda/bin:$PATH"
          source $HOME/miniconda/etc/profile.d/conda.sh
          conda create --name gcc_env -y
          conda activate gcc_env
          conda install -y gxx=14.2.0 gcc=14.2.0 bzip2 xz zlib zstd
          g++ --version
          gcc --version

    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload --skip-existing --repository-url https://upload.pypi.org/legacy/ wheelhouse/*
