name: Integration Tests - Linux

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.8"
            container: gcc:14.2
          - os: ubuntu-latest
            python-version: "3.9"
            container: gcc:14.2
          - os: ubuntu-latest
            python-version: "3.10"
            container: gcc:14.2

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
    - name: Checkout Mimir
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Install CMake
      run: |
        apt-get update
        apt-get install -y cmake

    - name: Configure, Build, and Install Dependencies
      run: |
        cd tests/integration/dependencies
        cmake -S . -B build -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/tests/integration/dependencies/installs"
        cmake --build build

    - name: Build and Test Project
      run: |
        cd tests/integration
        cmake -S . -B build -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/tests/integration/dependencies/installs"
        cmake --build build
