name: Pip - Linux

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.8"
            container: gcc:14.2
          - os: ubuntu-latest
            python-version: "3.9"
            container: gcc:14.2
          - os: ubuntu-latest
            python-version: "3.10"
            container: gcc:14.2

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install CMake
        run: |
          apt-get update
          apt-get install -y cmake

      - name: Install dependencies and requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools pytest

      - name: Build and install
        run: python -m pip install --verbose .[test]
        env:
          PYMIMIR_DEBUG_BUILD: 1

      - name: Test
        run: pytest python/tests
