name: Googletest Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Mimir
      uses: actions/checkout@v2
      with:
        ref: templated-design
      
    - name: Install Valgrind
      run: sudo apt-get install -y valgrind

    - name: Configure, Build, and Install Dependencies
      run: |
        cd dependencies
        cmake -S . -B build -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/dependencies/installs
        cmake --build build -j$(nproc)

    - name: Configure, and Build Mimir
      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -S . -B build -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/dependencies/installs
        cmake --build build -j$(nproc)


    - name: Test
      working-directory: build/tests/unit
      run: valgrind --leak-check=full --track-origins=yes ./mimir_tests

    - name: Test
      working-directory: build/tests/unit
      run: GTEST_OUTPUT=xml:test-results/ GTEST_COLOR=1 ctest -V --output-on-failure
